### PR TITLE
Comply with Server Name Identification standard

### LINKED ISSUE #10: Missing "servername" option to TLS
In addition to `hostname`, there should be a `servername` option in [these parameters](https://github.com/derhuerst/gemini/blob/master/client.js#L208). This will address the problem noted in this issue report on `gemini-fetch`.

https://github.com/RangerMauve/gemini-fetch/issues/1

### PR DESCRIPTION
**Pull request by bwestergard**
This resolves https://github.com/derhuerst/gemini/issues/10

### CODE REVIEW

**Comment by derhuerst** [comment]
Thanks!

**Comment by derhuerst** [comment]
Do you want to mentioned as a contributor in the `package.json` file? If you want to, with which string? `bwestergard`? `Björn Westergard` With an email address?

**Comment by bwestergard** [comment]
@derhuerst The last option (`Björn Westergard` with an email address) sounds good. Thanks!

**Comment by derhuerst** [comment]
Published as `@derhuerst/gemini@1.2.2`. 🎉

**Pull request merged**
